// <auto-generated />
using System;
using Infrastructure.DataBase;
using Infrastructure.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JWTProvider.Migrations
{
    [DbContext(typeof(UsersDBContext))]
    [Migration("20220621221615_SimplifyUserModel")]
    partial class SimplifyUserModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Infrastructure.DataBase.Password", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Passwords");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f2408735-baf9-4b7a-b133-33050bc2e86f"),
                            Hash = "mRytDVsoZEPR+eMiMbl/xMAckvL5s+k70iboHYpSIlw="
                        });
                });

            modelBuilder.Entity("Infrastructure.DataBase.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2408735-baf9-4b7a-b133-33050bc2e86f"),
                            Email = "test@mail.ru",
                            FirstName = "Денис",
                            LastName = "Алексеевич",
                            MiddleName = "Смирнов"
                        });
                });

            modelBuilder.Entity("Infrastructure.DataBase.Password", b =>
                {
                    b.HasOne("Infrastructure.DataBase.User", "User")
                        .WithOne("Password")
                        .HasForeignKey("Infrastructure.DataBase.Password", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.DataBase.User", b =>
                {
                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
