name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    uses: DaemonSharps/JWTProvider/.github/build.yml@master
      
  update_draft_release:
    name: Обновление черновика релиза
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release-drafter.outputs.tag_name }}
    steps:

      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_on_stage:
    name: Развертывание на стенды
    needs:
     - build
     - update_draft_release
    strategy:
      matrix:
        enviroment_name: [ development, production ]
        include:
          - enviroment_name: development
            version_tag: dev-${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}
          - enviroment_name: production
            version_tag: ${{ needs.update_draft_release.outputs.release_tag }}
    uses: DaemonSharps/JWTProvider/.github/docker-deploy.yml@master
    with:
      enviroment_name: ${{ matrix.enviroment_name }}
      version_tag: ${{ matrix.version_tag }}
    secrets:
      docker_login: ${{ secrets.DOCKER_USER_LOGIN }}
      docker_token: ${{ secrets.DOCKER_USER_AUTH_TOKEN }}