name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Сборка проекта .NET
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  update_draft_release:
    name: Обновление черновика релиза
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.release-drafter.outputs.tag_name }}
    steps:

      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_on_stage:
    needs:
     - build
     - update_draft_release
    strategy:
      matrix:
        enviroment-name: [ development, production ]
        include:
          - enviroment-name: development
            version-tag: dev
          - enviroment-name: production
            version-tag: ${{ needs.update_draft_release.outputs.tag_name }}
    uses: DaemonSharps/JWTProvider/.github/workflows/Docker-Deploy.yml@master
    with:
      enviroment-name: ${{ matrix.enviroment-name }}
      version-tag: ${{ matrix.version-tag }}
    secrets:
      docker-login: ${{ secrets.DOCKER_USER_LOGIN }}
      docker-token: ${{ secrets.DOCKER_USER_AUTH_TOKEN }}