name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    uses: DaemonSharps/CI-CD/.github/workflows/build.yml@master
      
  update_draft_release:
    name: Обновление черновика релиза
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release-drafter.outputs.tag_name }}
    steps:

      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_on_stage:
    name: Развертывание на стенды
    needs:
     - build
     - update_draft_release
    strategy:
      matrix:
        enviroment_name: [ development, production ]
        enviroment_name2: [ development, production ]
        enviroment_name3: [ development, production ]
        include:
          - enviroment_name: development
            version_tags: |
              daemonsharps/jwt-auth-api:dev-${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}
              daemonsharps/jwt-auth-api:dev-latest
          - enviroment_name: production
            version_tags: |
              daemonsharps/jwt-auth-api:${{ needs.update_draft_release.outputs.release_tag }}
              daemonsharps/jwt-auth-api:latest

    uses: DaemonSharps/CI-CD/.github/workflows/docker-deploy.yml@master
    with:
      enviroment_name: ${{ matrix.enviroment_name }}-${{ matrix.enviroment_name2 }}-${{ matrix.enviroment_name3 }}
      version_tags: ${{ matrix.version_tags }}
    secrets:
      docker_login: ${{ secrets.DOCKER_USER_LOGIN }}
      docker_token: ${{ secrets.DOCKER_USER_AUTH_TOKEN }}
